name: Deploy to Octenium

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy website
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Deploy with rsync
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-avz --delete"
        SOURCE: "./"
        REMOTE_HOST: ${{ secrets.OCTENIUM_HOST }}
        REMOTE_USER: ${{ secrets.OCTENIUM_USERNAME }}
        TARGET: ${{ secrets.OCTENIUM_TARGET_DIR }}

