import uuid
import json

# Complete dictionary of French motifs to Arabic translation
translations = {
    # MEDECINE GENERALE
    "Consultation de médecine générale": "استشارة طب عام",
    "Bilan de santé": "فحص طبي شامل",
    "Contrôle médical": "مراقبة طبية",
    "Suivi d'une maladie chronique": "متابعة مرض مزمن",
    "Fièvre": "حمى / ارتفاع الحرارة",
    "Fatigue": "تعب وإرهاق",
    "Douleurs générales": "آلام عامة بالجسم",
    "Maux de tête": "صداع / ألم الرأس",
    "Vertiges": "دوار / دوخة",
    "Malaise": "وعكة صحية / إغماء خفيف",
    "Toux": "سعال / كحة",
    "Rhume / symptômes grippaux": "زكام / أعراض الإنفلونزا",
    "Mal de gorge": "ألم في الحلق",
    "Douleurs abdominales": "آلام البطن",
    "Nausées / vomissements": "غثيان / قيء",
    "Diarrhée": "إسهال",
    "Constipation": "إمساك",
    "Douleurs musculaires": "آلام عضلية",
    "Douleurs articulaires": "آلام المفاصل",
    "Douleurs dorsales / lombaires": "آلام الظهر / أسفل الظهر",
    "Allergie": "حساسية",
    "Problème cutané": "مشكلة جلدية",
    "Infection suspectée": "اشتباه في عدوى",
    "Renouvellement d'ordonnance": "تجديد وصفة طبية",
    "Lecture / interprétation d'analyses": "قراءة وتفسير التحاليل الطبية",
    "Demande d'orientation vers un spécialiste": "طلب توجيه إلى طبيب مختص",
    "Certificat médical": "شهادة طبية",
    "Arrêt de travail": "عطلة مرضية / توقف عن العمل",
    "Aptitude médicale": "شهادة كفاءة طبية",
    "Vaccination": "تطعيم / تلقيح",
    "Prévention / conseils de santé": "وقاية ونصائح صحية",
    "Autre motif de consultation": "سبب استشارة آخر",

    # MEDECINE INTERNE
    "Consultation de médecine interne": "استشارة الطب الباطني",
    "Bilan diagnostique": "فحص تشخيصي شامل",
    "Bilan de symptômes persistants": "فحص الأعراض المستمرة",
    "Suivi d'une maladie systémique": "متابعة مرض جهازي",
    "Suivi d'une maladie auto-immune": "متابعة مرض مناعي ذاتي",
    "Suivi de plusieurs maladies chroniques": "متابعة أمراض مزمنة متعددة",
    "Fièvre prolongée": "حمى ممتدة / مستمرة",
    "Fatigue persistante": "تعب وإرهاق مزمن",
    "Perte de poids inexpliquée": "فقدان وزن غير مبرر",
    "Douleurs inexpliquées": "آلام غير مفسرة",
    "Bilan inflammatoire": "فحص الالتهابات",
    "Bilan immunologique": "فحص مناعي",
    "Bilan de maladies rares": "فحص الأمراض النادرة",
    "Suivi thérapeutique": "متابعة العلاج",
    "Avis spécialisé": "رأي طبي متخصص",

    # CARDIOLOGIE
    "Consultation de cardiologie": "استشارة أمراض القلب",
    "Bilan cardiovasculaire": "فحص القلب والأوعية الدموية",
    "Suivi d'hypertension artérielle": "متابعة ضغط الدم المرتفع",
    "Suivi d'insuffisance cardiaque": "متابعة قصور القلب",
    "Palpitations": "خفقان القلب",
    "Douleur thoracique": "ألم في الصدر",
    "Essoufflement": "ضيق في التنفس",
    "Malaise / syncope": "إغماء / فقدان الوعي",
    "Troubles du rythme cardiaque": "اضطراب نبضات القلب",
    "Bilan avant chirurgie": "فحص القلب قبل الجراحة",
    "Suivi après infarctus": "متابعة بعد الجلطة القلبية",
    "Suivi après intervention cardiovasculaire": "متابعة بعد عملية القلب والأوعية",
    "Contrôle de pacemaker / défibrillateur": "فحص ومراقبة جهاز تنظيم ضربات القلب",
    "Électrocardiogramme": "تخطيط كهربية القلب (ECG)",
    "Échocardiographie": "إيكوغرافيا القلب (Écho)",
    "Test d'effort": "اختبار الجهد للقلب",
    "Bilan des facteurs de risque cardiovasculaire": "تقييم عوامل الخطر القلبية",

    # DERMATOLOGIE
    "Consultation de dermatologie": "استشارة الأمراض الجلدية",
    "Acné": "حب الشباب",
    "Eczéma": "إكزيما",
    "Psoriasis": "صدفية",
    "Éruption cutanée": "طفح جلدي",
    "Démangeaisons": "حكة جلدية",
    "Rougeurs cutanées": "احمرار الجلد",
    "Taches cutanées": "بقع جلدية وتصبغات",
    "Lésion cutanée": "آفة / تشوه جلدي",
    "Grain de beauté / nævus": "شامة / حبة خال",
    "Contrôle d'un grain de beauté": "فحص ومراقبة الشامات",
    "Chute de cheveux": "تساقط الشعر",
    "Pellicules / problème du cuir chevelu": "قشرة / مشاكل فروة الرأس",
    "Infection cutanée": "عدوى جلدية",
    "Mycose cutanée": "فطريات الجلد",
    "Verrues": "ثآليل",
    "Herpès": "هربس (داء القبلة)",
    "Urticaire": "شرى / حساسية جلدية حادة",
    "Cicatrice": "ندبات وآثار جروح",
    "Brûlure": "حروق",
    "Plaie cutanée": "جروح وتقرحات جلدية",
    "Problème des ongles": "مشاكل وأمراض الأظافر",
    "Suivi d'une maladie dermatologique": "متابعة مرض جلدي",
    "Dépistage / contrôle des cancers cutanés": "كشف ومراقبة أورام الجلد",
    "Avis dermatologique": "استشارة رأي جلدي",

    # ENDOCRINOLOGIE / DIABETOLOGIE
    "Consultation d'endocrinologie": "استشارة الغدد الصماء والسكري",
    "Suivi du diabète": "متابعة داء السكري",
    "Bilan de diabète": "فحص شامل للسكري",
    "Équilibre glycémique": "ضبط ومراقبة مستوى السكر",
    "Suivi du diabète gestationnel": "متابعة سكري الحمل",
    "Hypoglycémie": "هبوط السكر في الدم",
    "Hyperglycémie": "ارتفاع السكر في الدم",
    "Bilan thyroïdien": "فحص الغدة الدرقية",
    "Suivi d'hypothyroïdie": "متابعة خمول الغدة الدرقية",
    "Suivi d'hyperthyroïdie": "متابعة نشاط الغدة الدرقية",
    "Nodule thyroïdien": "عقدة في الغدة الدرقية",
    "Maladie de la thyroïde": "أمراض الغدة الدرقية",
    "Trouble hormonal": "اضطراب الهرمونات",
    "Trouble de la croissance": "اضطرابات النمو",
    "Trouble de la puberté": "اضطرابات البلوغ",
    "Obésité": "سمنة مفرطة",
    "Surpoids": "زيادة الوزن",
    "Bilan métabolique": "فحص الأيض والتمثيل الغذائي",
    "Trouble du cholestérol": "اضطراب الكولسترول والدهون",
    "Trouble du calcium": "اضطراب الكالسيوم والمعادن",
    "Ostéoporose": "هشاشة العظام",
    "Suivi d'un traitement hormonal": "متابعة العلاج الهرموني",

    # GYNECOLOGIE / OBSTETRIQUE
    "Consultation gynécologique": "استشارة طب النساء",
    "Consultation de suivi gynécologique": "متابعة دورية لطب النساء",
    "Suivi de grossesse": "متابعة الحمل",
    "Première consultation de grossesse": "أول استشارة لتأكيد الحمل",
    "Suivi prénatal": "متابعة ما قبل الولادة",
    "Consultation postnatale": "استشارة ما بعد الولادة",
    "Contraception": "منع الحمل",
    "Choix / changement de contraception": "اختيار / تغيير وسيلة منع الحمل",
    "Pose de dispositif intra-utérin (DIU)": "تركيب اللولب الرحمي",
    "Contrôle de DIU": "فحص ومراقبة اللولب",
    "Retrait de DIU": "إزالة اللولب الرحمي",
    "Troubles des règles": "اضطرابات الدورة الشهرية",
    "Règles douloureuses": "آلام الدورة الشهرية",
    "Règles irrégulières": "عدم انتظام الدورة الشهرية",
    "Saignements gynécologiques": "نزيف نسائي غير طبيعي",
    "Douleurs pelviennes": "آلام الحوض وأسفل البطن",
    "Pertes vaginales": "إفرازات مهبلية غير طبيعية",
    "Démangeaisons génitales": "حكة في المنطقة الحساسة",
    "Infection gynécologique": "التهابات نسائية",
    "Ménopause": "سن اليأس وانقطاع الطمث",
    "Symptômes de ménopause": "أعراض سن اليأس",
    "Infertilité": "تأخر الإنجاب والعقم",
    "Bilan de fertilité": "فحص وتقييم الخصوبة",
    "Préconception": "استشارة ما قبل التخطيط للحمل",
    "Frottis / dépistage du col de l'utérus": "مسحة عنق الرحم (Frottis)",
    "Résultat de frottis": "قراءة نتائج مسحة الرحم",
    "Kyste ovarien": "تكيس المبيض / كيس المبيض",
    "Fibrome": "ورم ليفي رحمي (Fibrome)",
    "Endométriose": "بطانة الرحم المهاجرة (Endométriose)",
    "Suivi d'une pathologie gynécologique": "متابعة أمراض النساء",
    "Santé sexuelle": "الصحة الجنسية والإنجابية",

    "Première consultation prénatale": "أول فحص قبل الولادة",
    "Suivi du premier trimestre": "متابعة الثلث الأول من الحمل",
    "Suivi du deuxième trimestre": "متابعة الثلث الثاني من الحمل",
    "Suivi du troisième trimestre": "متابعة الثلث الثالث من الحمل",
    "Grossesse à risque": "حمل عالي الخطورة",
    "Surveillance de grossesse": "مراقبة دقيقة للحمل",
    "Échographie obstétricale": "إيكوغرافيا الحمل والجنين",
    "Dépistage prénatal": "كشف وفحص ما قبل الولادة",
    "Suivi de l'hypertension gravidique": "متابعة ضغط الدم أثناء الحمل",
    "Douleurs pendant la grossesse": "آلام أثناء الحمل",
    "Saignements pendant la grossesse": "نزيف أثناء الحمل",
    "Nausées / vomissements de grossesse": "غثيان وقيء الحمل",
    "Préparation à l'accouchement": "التحضير للولادة",
    "Consultation post-partum": "فحص فترة النفاس",
    "Suivi après accouchement": "متابعة ما بعد الولادة",

    # PEDIATRIE
    "Consultation pédiatrique": "استشارة طب الأطفال",
    "Consultation de suivi de l'enfant": "متابعة صحة ونمو الطفل",
    "Suivi du nouveau-né": "متابعة حديثي الولادة",
    "Bilan de croissance": "فحص الطول والوزن والنمو",
    "Bilan du développement": "تقييم التطور الحركي والذهني",
    "Fièvre chez l'enfant": "حمى عند الطفل",
    "Toux chez l'enfant": "سعال عند الطفل",
    "Rhume / symptômes ORL": "زكام والتهاب الأنف والحلق",
    "Douleur abdominale chez l'enfant": "مغص وآلام البطن عند الطفل",
    "Vomissements": "قيء واستفراغ",
    "Difficultés alimentaires": "صعوبات الرضاعة والتغذية",
    "Troubles du sommeil": "اضطرابات النوم",
    "Retard de croissance": "تأخر النمو البدني",
    "Retard du développement": "تأخر التطور والمهارات",
    "Troubles du comportement": "اضطرابات السلوك لدى الطفل",
    "Asthme": "ربو وضيق تنفس",
    "Difficultés respiratoires": "صعوبات في التنفس",
    "Bilan scolaire": "فحص طبي مدرسي",
    "Certificat médical enfant": "شهادة طبية للطفل",
    "Suivi du prématuré": "متابعة الأطفال الخدج",
    "Bilan néonatal": "فحص حديثي الولادة الشامل",
    "Difficultés d'alimentation": "صعوبة الرضاعة والأكل",
    "Prise de poids insuffisante": "ضعف زيادة الوزن",
    "Ictère néonatal": "اليرقان (بوصفير) لحديثي الولادة",
    "Suivi après hospitalisation néonatale": "متابعة بعد خروج الطفل من المستشفى",

    # OPHTALMOLOGIE
    "Consultation ophtalmologique": "استشارة طب وجراحة العيون",
    "Baisse de vision": "ضعف أو نقص حدة النظر",
    "Vision floue": "تشوش وضبابية في الرؤية",
    "Douleur oculaire": "ألم في العين",
    "Rougeur de l'œil": "احمرار العين",
    "Sécheresse oculaire": "جفاف العين",
    "Démangeaisons oculaires": "حكة وحساسية في العين",
    "Larmoiement": "إفراز دموع مفرط",
    "Infection oculaire": "التهاب وعدوى العين",
    "Maux de tête liés à la vision": "صداع ناتج عن إجهاد العين",
    "Contrôle de la vue": "فحص وقياس النظر",
    "Prescription / renouvellement de lunettes": "وصفة / تجديد النظارات الطبية",
    "Lentilles de contact": "فحص وتركيب العدسات اللاصقة",
    "Suivi de glaucome": "متابعة ضغط العين (الغلوكوما / الماء الأزرق)",
    "Dépistage du glaucome": "كشف ضغط العين (الغلوكوما)",
    "Suivi de cataracte": "متابعة إعتام عدسة العين (الماء الأبيض)",
    "Cataracte": "الماء الأبيض (الكاتاراكت)",
    "Suivi de rétinopathie diabétique": "متابعة شبكية العين لمرضى السكري",
    "Problème rétinien": "أمراض واعتلال الشبكية",
    "Contrôle après chirurgie oculaire": "مراقبة بعد عملية جراحية للعين",
    "Consultation pédiatrique ophtalmologique": "استشارة طب عيون الأطفال",

    # ORL
    "Consultation ORL": "استشارة الأنف والأذن والحنجرة",
    "Douleur d'oreille": "ألم في الأذن",
    "Baisse de l'audition": "نقص أو ضعف السمع",
    "Bourdonnements d'oreille": "طنين الأذن",
    "Écoulement de l'oreille": "إفرازات وسيلان من الأذن",
    "Sinusite": "التهاب الجيوب الأنفية",
    "Nez bouché": "انسداد الأنف وصعوبة التنفس الأنفي",
    "Saignement de nez": "رعاف / نزيف الأنف",
    "Difficultés respiratoires nasales": "صعوبة التنفس من الأنف",
    "Troubles de la voix": "اضطراب الصوت وبحة الصوت",
    "Enrouement": "بحة الصوت المستمرة",
    "Difficulté à avaler": "صعوبة وألم في البلع",
    "Ronflement": "الشخير أثناء النوم",
    "Apnée du sommeil": "انقطاع التنفس أثناء النوم",
    "Amygdales": "التهاب ومشاكل اللوزتين",
    "Troubles de l'équilibre": "اضطراب التوازن والدوخة الدهليزية",
    "Bilan auditif": "فحص وتخطيط السمع",
    "Suivi ORL": "متابعة أنف وأذن وحنجرة",

    # PNEUMOLOGIE
    "Consultation de pneumologie": "استشارة الأمراض الصدرية والتنفسية",
    "Toux persistante": "سعال وكحة مزمنة",
    "Sifflements respiratoires": "صفير وخشخشة في الصدر",
    "Suivi de BPCO": "متابعة الانسداد الرئوي المزمن (BPCO)",
    "Bronchite chronique": "التهاب الشعب الهوائية المزمن",
    "Infection respiratoire": "عدوى الجهاز التنفسي",
    "Pneumonie": "التهاب رئوي حاد",
    "Allergie respiratoire": "حساسية الجهاز التنفسي والربو",
    "Bilan respiratoire": "فحص وظائف الجهاز التنفسي",
    "Exploration fonctionnelle respiratoire": "قياس وظائف التنفس (EFR)",
    "Suivi après infection respiratoire": "متابعة بعد عدوى رئوية",
    "Sevrage tabagique": "المساعدة على الإقلاع عن التدخين",

    # GASTRO-ENTEROLOGIE
    "Consultation de gastro-entérologie": "استشارة أمراض الجهاز الهضمي",
    "Ballonnements": "انتفاخ وغازات البطن",
    "Reflux gastro-œsophagien": "ارتجاع المريء وحموضة المعدة",
    "Brûlures d'estomac": "حرقة وحموضة المعدة",
    "Nausées": "غثيان ولعيان النفس",
    "Diarrhée chronique": "إسهال مزمن",
    "Constipation chronique": "إمساك مزمن",
    "Sang dans les selles": "دم مع البراز",
    "Troubles digestifs": "عسر واضطرابات الهضم",
    "Intolérance alimentaire": "عدم تحمل الأغذية وحساسية الغلوتين",
    "Maladie inflammatoire intestinale": "أمراض الأمعاء الالتهابية (كرون / قولون)",
    "Syndrome de l'intestin irritable": "القولون العصبي (مصران خبيث/متهيج)",
    "Maladie du foie": "أمراض الكبد",
    "Bilan hépatique": "فحص وظائف الكبد",
    "Hépatite": "التهاب الكبد الفيروسي",
    "Calculs biliaires": "حصوات المرارة",
    "Maladie de la vésicule biliaire": "أمراض والتهاب المرارة",
    "Suivi de cirrhose": "متابعة تليف الكبد",
    "Coloscopie": "تنظير القولون (كولونوسكوبي)",
    "Gastroscopie / endoscopie": "تنظير المعدة (منظار علوي)",
    "Suivi après endoscopie": "متابعة ما بعد المنظار الهضمي",
    "Stéatose hépatique": "تشحم الكبد (الكبد الدهني)",
    "Fibrose hépatique": "تليف أنسجة الكبد",
    "Anomalie des enzymes hépatiques": "ارتفاع أنزيمات الكبد",
    "Douleur hépatique": "ألم في جهة الكبد",
    "Suivi d'une maladie du foie": "متابعة أمراض الكبد المزمنة",
    "Suivi après traitement": "متابعة بعد إنهاء العلاج",

    # NEPHROLOGIE
    "Consultation de néphrologie": "استشارة أمراض الكلى",
    "Bilan rénal": "فحص وتقييم وظائف الكلى",
    "Insuffisance rénale": "قصور وفشل الكلى",
    "Suivi d'insuffisance rénale chronique": "متابعة القصور الكلوي المزمن",
    "Protéinurie": "وجود بروتين (زلال) في البول",
    "Hématurie": "وجود دم في البول",
    "Hypertension d'origine rénale": "ارتفاع ضغط الدم الكلوي",
    "Œdèmes": "تورم وانتفاخ الجسم (وذمة)",
    "Troubles des électrolytes": "اضطراب أملاح ومعادن الدم",
    "Calculs rénaux": "حصى الكلى والمجاري البولية",
    "Suivi de dialyse": "متابعة الغسيل الكلوي (الدياليز)",
    "Préparation à la dialyse": "التحضير لبدء الغسيل الكلوي",
    "Suivi après transplantation rénale": "متابعة بعد زراعة الكلى",

    # UROLOGIE
    "Consultation d'urologie": "استشارة جراحة المسالك البولية",
    "Douleur urinaire": "ألم أثناء التبول",
    "Brûlures urinaires": "حرقة وحرارة البول",
    "Infection urinaire": "التهاب المجاري البولية",
    "Sang dans les urines": "دم في البول",
    "Difficultés à uriner": "صعوبة وتقطع التبول",
    "Urgences urinaires": "رغبة ملحة ومتكررة للتبول",
    "Incontinence urinaire": "سلس البول وتسرب غير إرادي",
    "Rétention urinaire": "احتباس البول الحاد",
    "Calculs urinaires": "حصى المسالك البولية والمثانة",
    "Douleur rénale": "مغص كلوي وألم الكلى",
    "Problèmes de prostate": "مشاكل وأمراض البروستات",
    "Hypertrophie bénigne de la prostate": "تضخم البروستات الحميد",
    "Dépistage / suivi de cancer de la prostate": "كشف ومتابعة أورام البروستات",
    "Troubles de l'érection": "ضعف واضطرابات الانتصاب",
    "Infertilité masculine": "عقم وتأخر الإنجاب عند الرجال",
    "Douleur testiculaire": "ألم أو تورم الخصية",
    "Suivi après chirurgie urologique": "متابعة بعد جراحة المسالك البولية",
    "Vasectomie / suivi": "ربط القنوات المنوية / متابعة",
    "Infection sexuellement transmissible": "أمراض منقولة جنسياً (IST)",
    "Dépistage IST": "فحص الأمراض المنقولة جنسياً",
    "Éjaculation précoce": "سرعة القذف",
    "Baisse de libido": "نقص الرغبة الجنسية",
    "Douleurs sexuelles": "آلام أثناء العلاقة الحميمية",
    "Troubles sexuels féminins": "اضطرابات الأداء الجنسي عند النساء",
    "Conseil en santé sexuelle": "استشارة وتوجيه في الصحة الجنسية",

    # NEUROLOGIE / NEUROCHIRURGIE
    "Consultation de neurologie": "استشارة طب المخ والأعصاب",
    "Migraine": "شقيقة / صداع نصفي",
    "Perte de connaissance": "فقدان الوعي المؤقت",
    "Convulsions": "تشنجات عصبية",
    "Épilepsie": "داء الصرع والتشنجات",
    "Tremblements": "رجفان ورعشة في اليدين أو الجسم",
    "Troubles de la mémoire": "مشاكل واضطراب الذاكرة",
    "Troubles de la concentration": "تشتت وضعف التركيز",
    "Fourmillements": "تنميل ووخز في الأطراف",
    "Engourdissements": "خدر وثقل الأطراف",
    "Faiblesse musculaire": "ضعف عضلي وثقل الحركة",
    "Paralysie": "شلل أو عجز حركي",
    "Douleurs nerveuses": "آلام عصبية حادة (عرق النسا وغيره)",
    "Neuropathie": "اعتلال والتهاب الأعصاب المحيطية",
    "Sclérose en plaques": "التصلب المتعدد (SEP)",
    "Maladie de Parkinson": "مرض باركنسون (الشلل الرعاش)",
    "Suivi neurologique": "متابعة عصبية دورية",
    "Bilan après AVC": "تقييم ومتابعة بعد الجلطة الدماغية (AVC)",
    "Consultation de neurochirurgie": "استشارة جراحة المخ والأعصاب",
    "Hernie discale": "انزلاق غضروفي (الديسك / الهرني)",
    "Compression nerveuse": "ضغط على الأعصاب والنخاع الشوكي",
    "Douleur rachidienne": "آلام العمود الفقري الحادة",
    "Sciatique": "عرق النسا / آلام العصب الوركي",
    "Douleur cervicale": "آلام الرقبة والفقرات العنقية",
    "Traumatisme crânien": "رضوض وإصابات الرأس والجمجمة",
    "Tumeur cérébrale": "أورام الدماغ",
    "Tumeur rachidienne": "أورام العمود الفقري والحبل الشوكي",
    "Avis neurochirurgical": "استشارة جراح مخ وأعصاب",
    "Suivi après chirurgie": "متابعة بعد عملية جراحية",

    # PSYCHIATRIE / PSYCHOLOGIE
    "Consultation psychiatrique": "استشارة الأمراض العقلية والنفسية",
    "Anxiété": "قلق وتوتر نفسي",
    "Crises d'angoisse": "نوبات هلع وخوف شديد",
    "Dépression": "اكتئاب وإحباط نفسي",
    "Troubles de l'humeur": "اضطراب المزاج وتقلباته",
    "Stress important": "ضغط نفسي وتوتر حاد",
    "Épuisement psychique": "إنهاك واستنزاف نفسي",
    "Troubles obsessionnels compulsifs": "وسواس قهري (TOC)",
    "Troubles alimentaires": "اضطرابات الشهية والأكل النفسية",
    "Addiction": "إدمان المواد أو السلوكيات",
    "Sevrage / accompagnement d'une addiction": "علاج ومرافقة الإقلاع عن الإدمان",
    "Trouble bipolaire": "الاضطراب ثنائي القطب",
    "Troubles psychotiques": "اضطرابات ذهانية وهلاوس",
    "Suivi psychiatrique": "متابعة نفسية وعقلية دورية",
    "Suivi d'un traitement psychiatrique": "متابعة الأدوية والعلاج النفسي",
    "Évaluation psychique": "تقييم وتشخيص نفسي شامل",
    "Consultation psychologique": "استشارة أخصائي نفسي",
    "Difficultés émotionnelles": "صعوبات وتحديات عاطفية",
    "Problèmes relationnels": "مشاكل واضطرابات العلاقات",
    "Difficultés familiales": "خلافات وصعوبات أسرية",
    "Deuil": "صدمة الفقدان والحداد",
    "Burn-out": "احتراق وظيفي وإرهاق العمل",
    "Difficultés scolaires": "صعوبات التعلم والدراسة",
    "Difficultés professionnelles": "مشاكل وضغوط بيئة العمل",
    "Accompagnement psychologique": "مرافقة وإرشاد نفسي",
    "Thérapie individuelle": "علاج نفسي فردي",
    "Thérapie de couple": "علاج نفسي للمتزوجين / الأزواج",
    "Thérapie familiale": "علاج وإرشاد أسري",

    # RHUMATOLOGIE / ORTHOPEDIE
    "Consultation de rhumatologie": "استشارة أمراض المفاصل والروماتيزم",
    "Mal de dos": "آلام الظهر",
    "Lombalgie": "ألم أسفل الظهر (اللومباغو)",
    "Cervicalgie": "ألم الرقبة والعنق",
    "Arthrose": "خشونة واحتكاك المفاصل (الأرتروز)",
    "Arthrite": "التهاب المفاصل الروماتويدي",
    "Polyarthrite rhumatoïde": "الروماتيزم المفصلي الحاد",
    "Goutte": "داء النقرس (داء الملوك)",
    "Douleurs inflammatoires": "آلام مفاصل التهابية",
    "Raideur articulaire": "تيبس وصعوبة حركة المفاصل",
    "Gonflement articulaire": "انتفاخ وتورم المفاصل",
    "Tendinite": "التهاب الأوتار",
    "Bursite": "التهاب الجراب الزلالي",
    "Fibromyalgie": "الألم العضلي الليفي (الفيبروميالغيا)",
    "Suivi d'une maladie rhumatismale": "متابعة مرض روماتيزمي مزمن",
    "Consultation orthopédique": "استشارة جراحة العظام والمفاصل",
    "Douleur osseuse": "آلام العظام",
    "Traumatisme": "رضوض وإصابات الحوادث",
    "Fracture": "كسور العظام",
    "Entorse": "التواء وتمزق الأربطة",
    "Luxation": "خلع في المفصل",
    "Douleur du genou": "ألم الركبة والغضروف المفصلي",
    "Douleur de l'épaule": "ألم الكتف وأوتاره",
    "Douleur de la hanche": "ألم مفصل الورك",
    "Douleur de la cheville": "ألم الكاحل",
    "Douleur du poignet": "ألم المعصم والرسغ",
    "Douleur du coude": "ألم المرفق والكوع",
    "Douleur du pied": "ألم القدم والكعب",
    "Déformation osseuse": "تشوهات واعوجاج العظام",
    "Problème ligamentaire": "إصابات وتمزق الأربطة الصليبية",
    "Problème tendineux": "مشاكل وتمزق الأوتار",
    "Suivi après fracture": "متابعة التئام الكسور وتثبيتها",
    "Contrôle après chirurgie orthopédique": "فحص ومراقبة بعد جراحة العظام",
    "Certificat médical sportif": "شهادة طبية لممارسة الرياضة",
    "Bilan médico-sportif": "فحص وتقييم رياضي شامل",
    "Aptitude sportive": "شهادة لياقة رياضية",
    "Douleur liée au sport": "آلام ناتجة عن النشاط الرياضي",
    "Blessure sportive": "إصابات الملاعب والرياضة",
    "Entorse sportive": "التواء ناتج عن الرياضة",
    "Tendinite sportive": "التهاب أوتار رياضي",
    "Reprise après blessure": "إعادة التأهيل بعد الإصابة الرياضية",
    "Suivi du sportif": "متابعة صحية للرياضيين",
    "Évaluation de la condition physique": "تقييم اللياقة والقدرة البدنية",

    # CHIRURGIE GENERALE
    "Consultation de chirurgie générale": "استشارة الجراحة العامة",
    "Avis chirurgical": "رأي وتقييم جراحي",
    "Douleur abdominale nécessitant un avis chirurgical": "ألم بطني حاد يتطلب تدخلاً جراحياً",
    "Hernie": "فتق بطني أو إربي (فتقة)",
    "Masse / boule": "كتلة أو ورم موضعي",
    "Kyste": "كيس دهني أو جلدي",
    "Lipome": "ورم شحمي حميد (ليبوم)",
    "Plaie": "جرح قطعي أو مفتوح",
    "Abcès": "خراج ودمل صديدي",
    "Problème de cicatrice": "مشاكل وتلوث الندبات الجراحية",
    "Suivi post-opératoire": "متابعة ورعاية ما بعد الجراحة",
    "Consultation préopératoire": "استشارة ما قبل العملية الجراحية",
    "Contrôle بعد intervention": "مراقبة بعد التدخل الجراحي",
    "Ablation de lésion": "استئصال كتلة أو تشوه جلدي",
    "Avis sur une intervention": "استشارة حول إجراء عملية جراحية",
    "Consultation de chirurgie vasculaire": "استشارة جراحة الأوعية الدموية",
    "Varices": "دوالي الساقين (الدفالي)",
    "Jambes lourdes": "ثقل وإجهاد الساقين",
    "Douleurs des jambes": "آلام الساقين والقدمين",
    "Gonflement des jambes": "تورم وانتفاخ القدمين والساقين",
    "Troubles de circulation": "اضطرابات الدورة الدموية في الأطراف",
    "Artériopathie": "انسداد واعتلال الشرايين المحيطية",
    "Plaie vasculaire": "جروح وقرحة ناتجة عن قصور الأوعية",
    "Ulcère": "قرحة الساقين المزمنة",
    "Anévrisme": "تمدد الأوعية الدموية (أم الدم / أنيفريزم)",
    "Suivi après intervention vasculaire": "متابعة بعد جراحة الأوعية والدوالي",

    # ONCOLOGIE / HEMATOLOGIE
    "Consultation d'oncologie": "استشارة طب الأورام والسرطان",
    "Bilan oncologique": "فحص وتقييم الأورام الشامل",
    "Suivi d'un cancer": "متابعة مرضى الأورام والسرطان",
    "Chimiothérapie": "العلاج الكيميائي ومتابعته",
    "Thérapie ciblée": "العلاج الموجه للأورام",
    "Immunothérapie": "العلاج المناعي للأورام",
    "Radiothérapie": "العلاج الإشعاعي ومتابعة آثاره",
    "Gestion des effets secondaires": "علاج الآثار الجانبية للأدوية والأورام",
    "Douleurs liées au cancer": "تسكين آلام مرضى الأورام",
    "Soins de support": "الرعاية التلطيفية والداعمة",
    "Surveillance après rémission": "مراقبة دورية بعد الشفاء التام",
    "Consultation d'hématologie": "استشارة أمراض الدم",
    "Anémie": "فقر الدم ونقص الحديد (أنيميا)",
    "Fatigue liée à une anémie": "إرهاق وخمول ناتج عن فقر الدم",
    "Anomalie de la numération sanguine": "خلل في تعداد خلايا الدم (FNS)",
    "Troubles de la coagulation": "اضطراب تخثر وتجلط الدم",
    "Saignements inhabituels": "نزيف متكرر غير معتاد",
    "Thrombose": "تجلط وخثرات الأوردة والشرايين",
    "Leucopénie": "نقص كرات الدم البيضاء",
    "Thrombopénie": "نقص الصفائح الدموية",
    "Maladie du sang": "أمراض واعتلالات خلايا الدم",
    "Suivi d'une maladie hématologique": "متابعة مرض دم مزمن",
    "Consultation douleur": "استشارة علاج وتسكين الآلام",
    "Douleur chronique": "علاج الآلام المزمنة المستعصية",
    "Douleur cancéreuse": "تسكين آلام الأورام",
    "Douleur neuropathique": "علاج آلام الأعصاب الحادة",
    "Douleur musculosquelettique": "آلام الجهاز العضلي الهيكلي",
    "Soins palliatifs": "رعاية تلطيفية للمرضى",
    "Accompagnement de fin de vie": "مرافقة ورعاية الحالات المتقدمة",
    "Gestion des symptômes": "التحكم في الأعراض المزعجة",

    # INFECTIOLOGIE
    "Consultation d'infectiologie": "استشارة الأمراض المعدية والوبائية",
    "Infection persistante": "عدوى بكتيرية أو فيروسية مستمرة",
    "Infection bactérienne": "عدوى بكتيرية",
    "Infection virale": "عدوى فيروسية",
    "Infection parasitaire": "طفيليات وعدوى معوية أو جلدية",
    "Infection tropicale": "أمراض المناطق الحارة والاستوائية",
    "Hépatite infectieuse": "التهاب الكبد الوبائي المعدي",
    "VIH": "فيروس نقص المناعة البشرية (السيدا / VIH)",
    "Tuberculose": "مرض السل (التدرن الرئوي)",
    "Infection récidivante": "عدوى متكررة ومتجددة",
    "Avis sur antibiothérapie": "استشارة واستخدام المضادات الحيوية",
    "Suivi d'une infection complexe": "متابعة حالات العدوى المعقدة",

    # ALLERGOLOGIE
    "Consultation d'allergologie": "استشارة أمراض الحساسية والمناعة",
    "Allergie alimentaire": "حساسية الأطعمة والأغذية",
    "Allergie médicamenteuse": "حساسية الأدوية والعقاقير",
    "Rhinite allergique": "التهاب وحساسية الأنف المزمنة",
    "Asthme allergique": "الربو التحسسي",
    "Eczéma allergique": "إكزيما وحساسية تلامسية",
    "Réaction allergique": "رد فعل تحسسي حاد",
    "Bilan allergologique": "فحص وتشخيص الحساسية الشامل",
    "Tests allergologiques": "اختبارات وخز الجلد للحساسية (Prick Test)",
    "Désensibilisation": "علاج إزالة التحسس المناعي",
    "Allergies saisonnières": "حساسية الربيع والمواسم (حبوب اللقاح)",

    # MEDECINE PHYSIQUE ET READAPTATION
    "Consultation de réadaptation": "استشارة الطب الفيزيائي وإعادة التأهيل",
    "Rééducation après accident": "إعادة التأهيل الحركي بعد الحوادث",
    "Rééducation après AVC": "إعادة التأهيل بعد الجلطة الدماغية",
    "Rééducation après chirurgie": "إعادة التأهيل والترويض بعد الجراحة",
    "Douleurs chroniques": "علاج الآلام الحركية المزمنة",
    "Handicap moteur": "تقييم ورعاية العجز والإعاقة الحركية",
    "Troubles de la mobilité": "صعوبة واضطراب المشي والحركة",
    "Réadaptation fonctionnelle": "إعادة التأهيل الوظيفي والاستقلالية",
    "Rééducation musculosquelettique": "ترويض وتقوية العضلات والمفاصل",
    "Rééducation neurologique": "إعادة التأهيل العصبي الحركي",
    "Prescription de rééducation": "وصف حصص الترويض الطبي (Kinésithérapie)",
    "Évaluation fonctionnelle": "تقييم القدرة الحركية والوظيفية",

    # DENTAIRE
    "Consultation dentaire": "استشارة طب وجراحة الأسنان",
    "Douleur dentaire": "ألم حاد في الضرس أو السن",
    "Carie": "تسوس الأسنان",
    "Sensibilité dentaire": "حساسية الأسنان للبرودة والحرارة",
    "Infection dentaire": "التهاب وعدوى الأسنان",
    "Abcès dentaire": "خراج والتهاب صديدي في اللثة أو السن",
    "Saignement des gencives": "نزيف اللثة أثناء تنظيف الأسنان",
    "Gingivite": "التهاب وتورم اللثة",
    "Parodontite": "التهاب أنسجة ودواعم السن",
    "Détartrage": "تنظيف وإزالة الجير من الأسنان (Détartrage)",
    "Contrôle dentaire": "فحص دوري لصحة الفم والأسنان",
    "Extraction dentaire": "خلع وقلع الأسنان أو ضرس العقل",
    "Dent cassée": "ترميم الأسنان المكسورة والمتآكلة",
    "Prothèse dentaire": "تركيب الأسنان الثابتة والمتحركة (طقم)",
    "Implant dentaire": "زراعة الأسنان (Implant)",
    "Orthodontie": "تقويم وتعديل اعوجاج الأسنان",
    "Contrôle orthodontique": "متابعة جهاز تقويم الأسنان",
    "Urgence dentaire": "طوارئ وعلاج ألم الأسنان الحاد",
    "Douleur maxillo-faciale": "آلام الفك والوجه",
    "Traumatisme facial": "إصابات ورضوض الوجه والفكين",
    "Fracture faciale": "كسور الفك وعظام الوجه",
    "Kyste buccal": "أكياس الفم والفكين",
    "Lésion buccale": "تقرحات وآفات تجويف الفم",
    "Problème de mâchoire": "مشاكل وصعوبة فتح الفك",
    "Articulation temporo-mandibulaire": "اضطراب مفصل الفك الصدغي (ATM)",
    "Extraction complexe": "خلع جراحي معقد لضرس العقل المدفون",
    "Avis chirurgical maxillo-facial": "استشارة جراحة الوجه والفكين",

    # RADIOLOGIE
    "Échographie": "فحص بالموجات فوق الصوتية (إيكوغرافيا)",
    "Échographie abdominale": "إيكوغرافيا البطن والكبد والكلى",
    "Échographie pelvienne": "إيكوغرافيا الحوض والرحم والمثانة",
    "Échographie mammaire": "إيكوغرافيا الثدي",
    "Radiographie": "أشعة سينية عادية (راديو X)",
    "Scanner / TDM": "أشعة مقطعية سكانير (TDM / Scanner)",
    "IRM": "رنين مغناطيسي (IRM)",
    "Mammographie": "أشعة الماموغرافي لفحص الثدي",
    "Doppler": "فحص الدوبلر لتدفق الأوعية والشرايين",
    "Imagerie musculosquelettique": "تصوير العظام والمفاصل والأوتار",
    "Imagerie neurologique": "تصوير المخ والعمود الفقري",
    "Imagerie thoracique": "تصوير الصدر والرئتين",
    "Imagerie abdominale": "تصوير أعضاء البطن",
    "Imagerie urologique": "تصوير الجهاز البولي والكلى",
    "Imagerie vasculaire": "تصوير الأوعية الدموية",
    "Contrôle / suivi radiologique": "متابعة ومقارنة الفحوصات الإشعاعية",

    # ANESTHESIE
    "Consultation pré-anesthésique": "استشارة التخدير قبل العملية الجراحية",
    "Évaluation avant chirurgie": "تقييم جاهزية المريض للجراحة",
    "Évaluation des risques anesthésiques": "تقييم مخاطر التخدير وتحديد نوعه",
    "Prise en charge de douleur chronique": "بروتوكول تسكين الآلام المزمنة",
    "Suivi après anesthésie": "متابعة الإفاقة والتعافي بعد التخدير",

    # MEDECINE ESTHETIQUE / PLASTIQUE
    "Consultation de médecine esthétique": "استشارة الطب التجميلي",
    "Acné et cicatrices": "علاج حب الشباب والندبات التجميلية",
    "Taches pigmentaires": "علاج التصبغات والكلف بالبشرة",
    "Rides": "علاج التجاعيد وحقن البوتوكس / الفيلر",
    "Relâchement cutané": "شد وتجديد نضارة البشرة والوجه",
    "Cicatrices": "تحسين وتجميل مظهر الندبات",
    "Traitement esthétique du visage": "علاجات تجميل ونضارة الوجه",
    "Traitement esthétique du corps": "علاجات نحت وتجميل الجسم",
    "Évaluation esthétique": "تقييم واستشارة تجميلية شاملة",
    "Consultation de chirurgie plastique": "استشارة جراحة التجميل والترميم",
    "Reconstruction après traumatisme": "ترميم التشوهات بعد الحوادث",
    "Reconstruction après brûlure": "ترميم آثار وعقود الحروق",
    "Malformation": "تصحيح العيوب والتشوهات الخلقية",
    "Reconstruction après cancer": "إعادة بناء الثدي وترميم آثار الأورام",
    "Plaie complexe": "علاج وترميم الجروح المعقدة",

    # NUTRITION
    "Consultation nutritionnelle": "استشارة التغذية والحمية العلاجية",
    "Perte de poids": "برنامج إنقاص الوزن والتخسيس",
    "Prise de poids": "برنامج زيادة الوزن وعلاج النحافة",
    "Diabète et nutrition": "حمية غذائية مخصصة لمرضى السكري",
    "Cholestérol et nutrition": "نظام غذائي لخفض الكولسترول والدهون",
    "Nutrition pendant la grossesse": "تغذية الحامل والمرضع الصحية",
    "Nutrition de l'enfant": "تغذية ونمو الرضع والأطفال",
    "Rééquilibrage alimentaire": "تعديل النمط الغذائي ونظام صحي متوازن",
    "Nutrition sportive": "تغذية وبناء أجسام للرياضيين",
    "Dénutrition": "علاج سوء التغذية ونقص الفيتامينات",
    "Consultation d'hépatologie": "استشارة أمراض الكبد المتخصصة",

    # MEDECINE DU SOMMEIL
    "Consultation du sommeil": "استشارة اضطرابات وأمراض النوم",
    "Insomnie": "الأرق وصعوبة النوم",
    "Somnolence diurne": "النعاس المفرط خلال النهار",
    "Réveils nocturnes": "الاستيقاظ المتكرر ليلاً",
    "Troubles du rythme veille-sommeil": "اضطراب الساعة البيولوجية للنوم",
    "Fatigue chronique liée au sommeil": "إرهاق مزمن ناتج عن قلة جودة النوم",
    "Bilan du sommeil": "تخطيط وفحص النوم الشامل (Polysomnographie)",

    # GENETIQUE
    "Consultation de génétique": "استشارة الأمراض الوراثية والجينية",
    "Conseil génétique": "استشارة وإرشاد وراثي للعائلة",
    "Antécédents familiaux": "دراسة التاريخ والأمراض الوراثية العائلية",
    "Suspicion de maladie génétique": "اشتباه في متلازمة أو مرض وراثي",
    "Maladie génétique connue": "متابعة ورعاية الأمراض الوراثية المؤكدة",
    "Diagnostic génétique": "تشخيص وتحاليل الجينات والكروموسومات",
    "Préconception et génétique": "فحص وراثي قبل الزواج والتخطيط للإنجاب",
    "Diagnostic prénatal génétique": "الفحص الوراثي للجنين قبل الولادة",

    # MEDECINE NUCLEAIRE
    "Scintigraphie": "فحص التصوير الومضاني (السانتيغرافي)",
    "TEP / PET scan": "فحص التصوير المقطعي البوزيتروني (PET Scan)",
    "Bilan oncologique en médecine nucléaire": "تقييم الأورام بالطب النووي",
    "Exploration fonctionnelle": "الفحوصات الوظيفية بالمواد المشعة",

    # ANATOMOPATHOLOGIE
    "Analyse anatomopathologique": "تحليل الأنسجة والخزعات المخبرية",
    "Biopsie": "فحص عينات وخزعات الأنسجة (Biopsie)",
    "Cytologie": "تحليل وفحص الخلايا (Cytologie)",
    "Analyse d'une pièce opératoire": "فحص الأنسجة المستأصلة جراحياً",
    "Deuxième avis anatomopathologique": "رأي مخبري ثانٍ في تحليل العينات",

    # TRANSVERSAUX
    "Deuxième avis médical": "أخذ رأي طبي ثانٍ",
    "Lecture d'analyses médicales": "قراءة وتفسير التحاليل الطبية",
    "Lecture d'un compte rendu d'imagerie": "قراءة وتفسير تقارير الأشعة والتصوير",
    "Consultation de suivi": "استشارة متابعة طبية",
    "Consultation après hospitalisation": "استشارة بعد الخروج من المستشفى",
    "Consultation après passage aux urgences": "استشارة بعد زيارة الطوارئ",
    "Bilan préopératoire": "فحوصات ما قبل التدخل الجراحي",
    "Bilan post-opératoire": "فحوصات ومتابعة ما بعد الجراحة",
    "Avis médical": "استشارة وإبداء رأي طبي",
    "Demande de dossier médical": "طلب واستخراج الملف الطبي",
    "Autre motif": "سبب آخر"
}

# Mapping sections to our 27 DB Specialties
section_to_specialty_ar = {
    "MEDECINE GENERALE": "طب عام",
    "MEDECINE DU TRAVAIL": "طب عام",
    "MEDECINE D'URGENCE": "طب عام",
    "AUTRES MOTIFS TRANSVERSAUX": "طب عام",
    
    "MEDECINE INTERNE": "الطب الباطني (داخلي)",
    "GERIATRIE": "الطب الباطني (داخلي)",
    "GENETIQUE MEDICALE": "الطب الباطني (داخلي)",
    "PATHOLOGIE / ANATOMOPATHOLOGIE": "الطب الباطني (داخلي)",
    
    "CARDIOLOGIE": "طب أمراض القلب",
    
    "DERMATOLOGIE": "الأمراض الجلدية والتناسلية",
    
    "ENDOCRINOLOGIE / DIABETOLOGIE": "مرض السكري و الغدد الصماء",
    
    "GYNECOLOGIE": "طب النساء والتوليد",
    "OBSTETRIQUE": "طب النساء والتوليد",
    "REPRODUCTION / FERTILITE": "طب النساء والتوليد",
    
    "PEDIATRIE": "طب وجراحة الأطفال",
    "NEONATOLOGIE": "طب وجراحة الأطفال",
    "CHIRURGIE PEDIATRIQUE": "طب وجراحة الأطفال",
    
    "OPHTALMOLOGIE": "طب وجراحة العيون",
    
    "ORL": "طب وجراحة الأنف والأذن والحنجرة",
    
    "PNEUMOLOGIE": "طب الأمراض الصدرية و الجهاز التنفسي",
    
    "GASTRO-ENTEROLOGIE": "طب الجهاز الهضمي",
    "HEPATOLOGIE": "طب الجهاز الهضمي",
    
    "NEPHROLOGIE": "أخصائي أمراض الكلى",
    
    "UROLOGIE": "طب وجراحة المسالك البولية",
    "SANTE SEXUELLE": "طب وجراحة المسالك البولية",
    
    "NEUROLOGIE": "طب وجراحة المخ و الأعصاب",
    "NEUROCHIRURGIE": "طب وجراحة المخ و الأعصاب",
    "MEDECINE DU SOMMEIL": "طب وجراحة المخ و الأعصاب",
    
    "PSYCHIATRIE": "الامراض العقلية و النفسية",
    "PSYCHOLOGIE": "الامراض العقلية و النفسية",
    
    "RHUMATOLOGIE": "طب العظام و المفاصل",
    "ORTHOPEDIE / TRAUMATOLOGIE": "طب العظام و المفاصل",
    "MEDECINE DU SPORT": "طب العظام و المفاصل",
    
    "CHIRURGIE GENERALE": "جراحة عامة",
    "CHIRURGIE VASCULAIRE": "جراحة عامة",
    
    "ONCOLOGIE": "طب أمراض الدم والأورام",
    "HEMATOLOGIE": "طب أمراض الدم والأورام",
    "SOINS PALLIATIFS / DOULEUR": "طب أمراض الدم والأورام",
    
    "INFECTIOLOGIE": "الأمراض المعدية",
    
    "ALLERGOLOGIE / IMMUNOLOGIE": "أمراض الحساسية",
    
    "MEDECINE PHYSIQUE ET READAPTATION": "الطب الفيزيائي وإعادة التأهيل الحركي",
    
    "DENTAIRE / ODONTOLOGIE": "طب وجراحة الأسنان",
    "STOMATOLOGIE / CHIRURGIE MAXILLO-FACIALE": "طب وجراحة الأسنان",
    
    "RADIOLOGIE / IMAGERIE MEDICALE": "علم الأشعة_راديولوجي",
    
    "ANESTHESIOLOGIE": "طب التخدير",
    
    "MEDECINE ESTHETIQUE": "طب وجراحة تجميلية",
    "PLASTIQUE / RECONSTRUCTRICE": "طب وجراحة تجميلية",
    
    "NUTRITION / DIETETIQUE": "طب التغذية و الحمية",
    
    "MEDECINE NUCLEAIRE": "الطب النووي"
}

print("Mappings and translations defined.")
